---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  become: false
  connection: local
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "getsreya/mini-calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -p 8080:8080 -d getsreya/mini-calculator